# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Philosopher.destroy_all 

Philosopher.create(name: "Friedrich Nietzsche", summary: "Friedrich Nietzsche (1844–1900) was a German philosopher and cultural critic who published intensively in the 1870s and 1880s. He is famous for uncompromising criticisms of traditional European morality and religion, as well as of conventional philosophical ideas and social and political pieties associated with modernity.", image: "https://lh3.googleusercontent.com/FC9P4zz0fcFExqu6ElbalPxJGwd9aH7suwaJXIVqI7pJOyso_9TtqybK99o1WYReVmdwPWEm1Zq4FtDd0XIu97uEXIUtggpC6OA5EZLcCAZBd38Z8cDVk5e19sKxfv9QlxlsplPnzg=w2400")
Philosopher.create(name: "Martin Heidegger", summary: "Martin Heidegger (1889–1976) was a German philosopher whose work is perhaps most readily associated with phenomenology and existentialism, although his thinking should be identified as part of such philosophical movements only with extreme care and qualification. His ideas have exerted a seminal influence on the development of contemporary European philosophy.", image: "https://lh3.googleusercontent.com/8eqdAUjU77jHXR7GThdMMJT4pPnkeGBCQ7xTXEpXrnsNdUVN1Wr2J528PmQuAHoxCJP0U_kE4LZeKt6s_inCfCIipOrXOS9ubp03n1Yoe0hk-jV985j49p8XSPXEMioSDzcc9FQwZg=w2400")
Philosopher.create(name: "Søren Kierkegaard", summary: "Søren Aabye Kierkegaard (b. 1813, d. 1855) was a profound and prolific writer in the Danish “golden age” of intellectual and artistic activity. His work crosses the boundaries of philosophy, theology, psychology, literary criticism, devotional literature and fiction.", image: "https://lh3.googleusercontent.com/LiQh95f_buPnS_lvWrj-qu7oJtNhtvzvuwAkVv98UqoYFww1OPykHvrNiTQ9X2E24_J6M8iMRxSU_jeFZ2sRljtUBceZa9tOD5q5Ykpzvrh19oDfu8UmLkhj3Jn3eFkvc8fF5NTN5Q=w2400")
Philosopher.create(name: "Hannah Arendt", summary: "She is best known for two works that had a major impact both within and outside the academic community. The first, The Origins of Totalitarianism, published in 1951, was a study of the Nazi and Stalinist regimes that generated a wide-ranging debate on the nature and historical antecedents of the totalitarian phenomenon. The second, The Human Condition, published in 1958, was an original philosophical study that investigated the fundamental categories of the vita activa (labor, work, action).", image: "https://lh3.googleusercontent.com/XExkg0n4ImVmKQ6ROt5uzTIiEduqtw6dGgNbouz-TJZoeY6MuaHHFMXo59BVSlrPMm8fjgbTepKB-x4GFUzXNVmTPf_594f3MIJC83moeXIuDIw9EG0fkqBTw3vkCC37thuXXGbRqw=w2400")
Philosopher.create(name: "Emil Cioran", summary: "Emil Cioran (1911 – 1995) was a Romanian philosopher and essayist, who published works in both Romanian and French. His work has been noted for its pervasive philosophical pessimism, and frequently engages with issues of suffering, decay, and nihilism.", image: "https://lh3.googleusercontent.com/jp82i4wyIv1Jk4zxQeRbq64o0E-B59T5ELMXOr8NZTmYLqOh2aFWAi0_Qh6KnwqEhc3lUKTKO8Y577_vXmkhoQftT5rvyorsn-QLeTupbkFsNob0zRMsbj-qz8C8wFocGJXy9SgdmA=w2400")
Philosopher.create(name: "Arthur Schopenhauer", summary: "Arthur Schopenhauer was among the first 19th century philosophers to contend that at its core, the universe is not a rational place. Inspired by Plato and Kant, both of whom regarded the world as being more amenable to reason, Schopenhauer developed their philosophies into an instinct-recognizing and ultimately ascetic outlook, emphasizing that in the face of a world filled with endless strife, we ought to minimize our natural desires for the sake of achieving a more tranquil frame of mind and a disposition towards universal beneficence.", image: "https://lh3.googleusercontent.com/Bsx7fi0O-lY-0IpYxuZIRYl0iy45gYpYA3OUy9CjdPfyGY10ojvF84xb8rXhm5QHsBxIK3DP9HhUKE_MxqcAw8LzO17BgYLlKoIWXk53WZ3OcuTdzHtzBc8t135AGcDQ3u2hSAHlVg=w2400")
Philosopher.create(name: "Karl Marx", summary: "Karl Marx (1818–1883) is best known not as a philosopher but as a revolutionary, whose works inspired the foundation of many communist regimes in the twentieth century. It is hard to think of many who have had as much influence in the creation of the modern world. Trained as a philosopher, Marx turned away from philosophy in his mid-twenties, towards economics and politics.", image: "https://lh3.googleusercontent.com/MUfz5KQTdyTLdR3BcRCoj8Tpu6FhE9NHsNt-KG38Item_4lgxiajDTJF981gcMWrK-8oddrIcmSFfeFPXWmGcJz8mKeef0sJC7iFsN0ldwqNHUd3pO9Detqe5hBMM6pIE0PpY81XSg=w2400")
Philosopher.create(name: "Slavoj Žižek", summary: "Slavoj Žižek (born 21 March 1949) is a Slovenian philosopher, currently a researcher at the Department of Philosophy of the University of Ljubljana Faculty of Arts, and International director of the Birkbeck Institute for the Humanities of the University of London.[3] He is also Global Eminent Scholar at Kyung Hee University in Seoul and Global Distinguished Professor of German at New York University. He works in subjects including continental philosophy, political theory, cultural studies, psychoanalysis, film criticism, Marxism, Hegelianism and theology." , image: "https://lh3.googleusercontent.com/hs_hiEr4PywzKWmVb1Cr9c3RItEK43B4Q13NKTT7RFHaWO-2xL2Q2QhhyexqHEycQ5cqd2nbD-vDwKR69PIezgbib-co5QRGhojIsL_OMOZgtyqsFdaYNUlDhnd_HKRL2ESVIK9Wcw=w2400")
Philosopher.create(name: "Simone Weil", summary: "Simone Weil (1909–1943) philosophized on thresholds and across borders. Her persistent desire for truth and justice led her to both elite academies and factory floors, political praxis and spiritual solitude. At different times she was an activist, a pacifist, a militant, a mystic, and an exile; but throughout, in her inquiry into reality and orientation to the good, she remained a philosopher. ", image: "https://lh3.googleusercontent.com/8-sEmNQsG6e17a_8755FsT8IQvyBkzw71YWv4-0qTK8NqjNp0YuMtdFVkcWtws8qYhh8vj5Al99fT36kThaOtJvY_j1L1CytXB5fpHmD7dlwtKV8vnSltdDBraXhkuYOFimiNEMuvw=w2400")
Philosopher.create(name: "Susan Sontag", summary: "Susan Sontag (1933 – 2004) was an American writer, filmmaker, philosopher, teacher, and political activist. She mostly wrote essays, but also published novels; she published her first major work, the essay 'Notes on 'Camp',' in 1964. Her best-known works include On Photography, Against Interpretation, Styles of Radical Will, The Way We Live Now, Illness as Metaphor, Regarding the Pain of Others, The Volcano Lover, and In America.", image: "https://lh3.googleusercontent.com/TKHtx99c0TgulasMZMpnTtIxHBEPGPFseVD25LRT-Th_5iHdEoceV2NRcE3ci1Mg93kUVoNN1oZzFy87chYKVVGErfO7AQFqoz1wtjv_r07UUSLfjaq7EkTqLHjtYOypdgo-eiTCPA=w2400")

